name : magicc-mesmer-gmd
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - cartopy
  - flake8
  - ipywidgets
  - isort
  - mesmer==0.8.3
  - netcdf4
  - dask
  - statsmodels==0.12.2
  - matplotlib<3.3
  - nb_black
  - notebook
  - regionmask==0.8.0
  - scmdata==0.9.1
  - shapely<1.8
  - xarray==0.17.0

